# Generated by Django 3.2 on 2021-04-24 01:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do livro')),
                ('qtd_pagina', models.IntegerField(verbose_name='Páginas')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('data_inclusao', models.DateField(default=datetime.datetime.now, verbose_name='Data de inclusão')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autor.autor', verbose_name='Autor')),
            ],
        ),
    ]
